[package]
name = "black_scholes"
version = "0.1.0"
description = "A minimal template for developing with Cairo 1.0"
homepage = "https://github.com/auditless/cairo-template"

[scripts]
sierra = "cairo-compile . -r"
test = "cairo-test ."

[dependencies]
cubit = { git = "https://github.com/0xsachaeth/cubit.git" }
